### ISSUE TITLE
Handlebars: Dynamic requires are not currently supported by rollup-plugin-commonjs

### ISSUE THREAD

**Issue by jasonwaters** [rollup/rollup-plugin-commonjs#131] opened 2016-10-14 18:14 UTC
This is probably the wrong place to ask this, but I'm getting this error when trying to use handlebars in my rollupjs build:

`Dynamic requires are not currently supported by rollup-plugin-commonjs`

I'm trying to figure out how I can include Handlebars `import Handlebars from 'handlebars';
` for use in my project using rollupjs.  Any ideas?

**Comment by Gothdo** [comment] 2016-10-30 21:36
I'm getting the same error with Sinon.js.

**Comment by thisconnect** [comment] 2016-10-31 11:30
This is is far as I know:

commonjs allows to do conditional requires
```js
if (something){
  dep = require('foo')
}
```

es modules are static and do NOT allow conditional imports. So the example can not be converted to imports/exports


Looking at the handlebars.js source code... They moved partly to es modules, but index.js requires some dist/cjs files.

Wild guess: Could you try to import from the es modules directly? Something like `import Handlebars from 'handlebars/lib/handlebars.js';`

**Comment by krstffr** [comment] 2017-06-13 12:16
I also have this error using [mongoose](https://github.com/Automattic/mongoose)!

I've created a [minimal repo](https://github.com/krstffr/rollup-mongoose-bug) with the bug for reproduction.

**Comment by sgwatgit** [comment] 2017-08-27 02:13
I ran into this issue and I'm also using Typescript (so I wanted to still be able to use `@types/handlebars`).

I created a `typings.d.ts` along side the files that use `import Handlebars from 'handlebars/lib/handlebars.js';`. It contains the following lines

```
declare module "handlebars/lib/handlebars" {
    export default Handlebars;
}
```

The reason I'm doing this is I'm trying to use ES Modules natively in the browser (with Chrome 61) but I want my `node_modules` dependencies to be bundled separately from my application code as ES Modules, which was the approach [recommended in this youtube video](https://youtu.be/fIP4pjAqCtQ?t=24m56s).

Here is a demo app I made showing the workarounds/steps needed to use ES Modules in the browser without transpiling/polyfilling them
https://github.com/sgwatgit/ts-to-es2015

**Comment by franciscop** [comment] 2018-06-23 07:56
@thisconnect that worked surprisingly well for me! Thanks!

**Comment by svedova** [comment] 2018-11-10 19:04
For me it worked to include this option in `rollup.config.js`: 

```
commonJs({ 
  ignore: ["conditional-runtime-dependency"] 
})
```

**Comment by soullivaneuh** [comment] 2019-11-23 22:04
I ran into this issue just by importing `casual`:

```
import casual from 'casual';
```

If I remove this line, everything works. I'm not very sure of what to do.

I tried https://github.com/rollup/rollup-plugin-commonjs/issues/131#issuecomment-437611702 without any luck.

**Comment by shellscape** [comment] 2019-11-24 18:11
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed by shellscape** 2019-11-24 18:11 UTC
Labels: enhancement
