### ISSUE TITLE
Can not consume UMD file bundled by rollup

### ISSUE THREAD

**Issue by leeyeh** [rollup/rollup-plugin-commonjs#139] opened 2016-11-09 11:10 UTC
I'v got a UMD file bundled by rollup:
```javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define('leancloud-realtime', ['exports'], factory) :
	(factory((global.AV = global.AV || {})));
}(this, (function (exports) { 
        var Realtime = 1;
	exports.Realtime = Realtime;
	Object.defineProperty(exports, '__esModule', { value: true });
})));
```

when trying to consume it with rollup-plugin-commonjs, an Error was thrown: `'Realtime' is not exported by umd.js`.

To reproduce, clone https://github.com/leeyeh/rollup-plugin-commonjs-issue-umd and run `npm run build`.

**Comment by Rich-Harris** [comment] 2016-12-14 16:57
You'll need to use the `namedExports` option. Recent versions of Rollup will print the following message:

> 'Realtime' is not exported by umd.js (imported by index.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

```diff
import commonjs from 'rollup-plugin-commonjs';

export default {
    entry: 'index.js',
    plugins: [commonjs({
        include: ['umd.js'],
+        namedExports: {
+            'umd.js': [ 'Realtime' ]
+        }
    })],
    dest: 'bundle.js',
    format: 'cjs',
};

**Comment by leeyeh** [comment] 2016-12-15 05:23
`namedExports` works of course, but it's not what I'm looking for.

I have a SDK to be consumed by other developers. It uses rollup with target format in umd. Recently it has been reported that it can not be imported in Ionic2, which uses rollup as the bundler as well. 

So my question is, as a SDK provider, how to bundle a file so it can be consumed by rollup-plugin-commonjs?

**Comment by DanielJoyce** [comment] 2017-01-26 19:05
Also named exports doesn't always work either.

**Comment by udos86** [comment] 2017-02-11 10:09
Hi! I'm facing the exact same problem @leeyeh described. 

I'm developing an [Angular 2 library](https://github.com/udos86/ng2-dynamic-forms) which is provided via UMD files that are built with Rollup itself. 

But for a reason I don't know it is not possible to bundle these UMD files with Rollup for production.

```
Error: 'DynamicFormsCoreModule' is not exported by node_modules/@ng2-dynamic-forms/core/bundles/core.umd.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
example/app/app.module.js (12:9)
10: import { ReactiveFormsModule, NG_VALIDATORS } from "@angular/forms";
11: import { MaterialModule } from "@angular/material";
12: import { DynamicFormsCoreModule } from "@ng2-dynamic-forms/core";
             ^
13: import { DynamicFormsBasicUIModule } from "@ng2-dynamic-forms/ui-basic";
14: import { DynamicFormsBootstrapUIModule } from "@ng2-dynamic-forms/ui-bootstrap";
```

I've now spend two days on this and I cannot get my head around it because whenever I check my UMD files they actually do export everything:

```
exports.DynamicFormsCoreModule = DynamicFormsCoreModule_1 = (function () {
    function DynamicFormsCoreModule() {
    }
    DynamicFormsCoreModule.forRoot = function () {
        return {
            ngModule: DynamicFormsCoreModule_1,
            providers: [
                exports.DynamicFormService,
                DynamicFormAutoFillService,
                exports.DynamicFormRelationService
            ]
        };
    };
    return DynamicFormsCoreModule;
}());
exports.DynamicFormsCoreModule = DynamicFormsCoreModule_1 = __decorate$20([
    _angular_core.NgModule({
        imports: [_angular_common.CommonModule, _angular_forms.ReactiveFormsModule],
        declarations: [exports.DynamicIdDirective, exports.DynamicTemplateDirective],
        exports: [exports.DynamicIdDirective, exports.DynamicTemplateDirective]
    })
], exports.DynamicFormsCoreModule);
```

What's even more weird is that I'm using the identical gulp task that Angular 2 Material does for building my UMD files. However for the @angular/material UMD bundle no exception is ever thrown.

I really like Rollup. It's a great tool!

But for the moment I have to advise all users of my library to switch to Webpack 2 instead because it bundles the UMD files like a charm. 

@Rich-Harris Could you please help? Thanks very much!

**Comment by marcinczenko** [comment] 2018-04-24 10:33
namedExports does not seem to work for me. I am using monorepo and packages with scopes. I get errors like this: 

```
'DemoProvider' is not exported by ../demo-package/umd/demo-package.min.js
```

and my commonjs plugin has the following:

```
commonjs({
      include: /node_modules/,
      namedExports: {
        '../demo-package/umd/demo-package.min.js': ['DemoProvider']
      }
    })
```

and I tried this on a number of packages that I have, non of them work.

When I switch to use regular commonjs (so not umd), I am getting:

```
'DemoProvider' is not exported by ../demo-package/lib/index.js
```

Maybe the problem is hoisting and yarn workspaces? Or using scoped packages is a problem?

We do not depend heavily on that feature and we discovered it only when testing our umd bundles. All our packages have `pkg.module` and it works well with rollup, but it feels a bit wrong that we also produce umd bundles (with rollup) and rollup will not be able to consume them...

**Comment by bterlson** [comment] 2019-08-08 21:32
Duplicate of #159.

**Closed by bterlson** 2019-08-08 21:32 UTC
Labels: bug

**Comment by stefcameron** [comment] 2019-09-19 20:52
@marcinczenko Thank you for your detailed analysis. I'm still running into this a year and a half later (unbelievable!) and was able to get around the issue of "Error: default is not exported by..." thanks to your findings. 😄This should be way more intuitive than it is.
