### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-plugin-commonjs#6] opened 2015-11-02 14:44 UTC
browserify defines `global` as `window` alias

For example this lib fails in browser
https://github.com/jbraithwaite/scroll-to-y

**Comment by Rich-Harris** [comment] 2015-11-02 16:40
Don't have time to implement this right now, but I reckon the best fix is to detect whether `global` is referenced in any CommonJS modules (this is fairly straightforward thanks to some stuff that got added for 1.2.0), and if so, add an intro to the bundle and add `global` to each module like so:

```js
// intro for the whole bundle
var commonjsGlobal = typeof window !== 'undefined' ? window :
                     typeof global !== 'undefined' ? global :
                     this;

// individual module
var foo = (function (module, global) {
var exports = module.exports;
/* commonjs module happens */
return module.exports;
}({exports:{}}, commonjsGlobal);

export default foo;
```

**Comment by Rich-Harris** [comment] 2015-11-07 20:44
Added and released as 1.3.0

**Comment by TrySound** [comment] 2015-11-07 20:45
@Rich-Harris Thanks!

**Comment by hugomallet** [comment] 2016-01-06 09:58
Hi,

An issue with Underscore.js that probably relates to this one:

```bash
var previousUnderscore = root._;
                               ^

TypeError: Cannot read property '_' of undefined
````

Reproduce:

- lib.js

```js
import _ from 'underscore';

export default function foo() {
	return _.map([1, 2, 3], function(num){ return num * 3; });
}
````

- rollup-config.js

```js
import commonjs from 'rollup-plugin-commonjs';
import npm from 'rollup-plugin-npm';

export default {
	entry: 'lib.js',
	dest: 'lib-bundle.js',
	format: 'cjs',
	plugins: [
		npm({
			main: true
		}),
		commonjs()
	]
}
````

- execute

```bash
rollup -c rollup-config.js
node lib-bundle.js
```

**Comment by Rich-Harris** [comment] 2016-01-19 02:01
@hugomallet This might have been related to #31, and if so would be fixed now – please open a new issue if not

**Comment by herrstucki** [comment] 2016-06-23 20:08
This happens again with v3.0.1 in combination with `babel-polyfill`:

```
    if (global._babelPolyfill) { // <--- here
      throw new Error("only one instance of babel-polyfill is allowed");
    }
```

Works fine with v2.2.1.

**Comment by StreetStrider** [comment] 2016-07-09 20:36
@herrstucki, hello.
I've faced `global is not defined` issue too. I'm not sure what is the current status of this? I've updated to ` rollup-plugin-commonjs@3.1.0` and still have this. Should this module convert `global` to `window` or there're some reasons not to do it which I don't know about? Can you help with this?

I see some attempts to capture proper global object in my bundle, but seems they are not enough.

**Comment by TrySound** [comment] 2016-07-09 20:46
@StreetStrider this plugin generates this stuff
```js
typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {}
```
Produce please minimal example

**Comment by StreetStrider** [comment] 2016-07-09 20:57
@TrySound, yes I've detected this in my bundle. This expr assigned to name `commonjsGlobal`. But for some reason some of my bundled deps do not reassign its `global` refs to `commonjsGlobal` which leads to an error. I've tried to create minimal reproducible repo now, but everything works OK in it. Looks that something is wrong in my real (and more complex) bundle. Will try to make it reproducible or to find issue on my side.

**Comment by StreetStrider** [comment] 2016-07-09 21:24
Got [this code](https://github.com/socketio/has-binary/blob/73875a20978a219f726f7d313ccd1de19335f5a1/index.js#L28-L32) transformed into:
```js
        if ( (global.Buffer && global.Buffer.isBuffer(obj)) ||
             (global.ArrayBuffer && obj instanceof ArrayBuffer) ||
             (global.Blob && obj instanceof Blob) ||
             (commonjsGlobal.File && obj instanceof File)
            ) {
```
in my bundle. Still digging.

**Comment by StreetStrider** [comment] 2016-07-09 22:13
@TrySound, problem dissolves after clear install. Looks like something in caches or elsewhere obscures me. Everything works ok on `rollup-plugin-commonjs@3.1.0`. whew

**Closed** 2016-07-09 23:52 UTC

**Comment by itsazzad** [comment] 2017-02-07 11:16
```
Uncaught ReferenceError: global is not defined
    at index.js:388
    at empty (index.js:4)
    at index.js:5
```
```js
import 'fabric';

// create a wrapper around native canvas element (with id="c")
var canvas = new fabric.Canvas('c');

// create a rectangle object
var rect = new fabric.Rect({
  left: 100,
  top: 100,
  fill: 'red',
  width: 20,
  height: 20
});

// "add" rectangle onto canvas
canvas.add(rect);
```

**Comment by antony** [comment] 2019-07-19 15:16
I get this trying to include

```js
  import MapboxGeocoder from '@mapbox/mapbox-gl-geocoder'
```

No time to produce a minimal example right now, but I will as soon as possible - just wanted to confirm this as an ongoing issue.

**Comment by vitalis-wiens** [comment] 2019-08-08 14:16
I had the same issue. I have found a workaround(hack).

In rollup.config.js :

``` 
output: {
  sourcemap: true,
  format: 'iife',
  name: 'app',
  file: 'public/bundle.js',
  
   // <<<<<< adds this line into the bundle.js >>>>>>>  const global = window;
   intro: 'const global = window;'
		
},
```

This defines the variable 'global' at the beginning of the bundle. 

I am somewhat new to the whole bundling process and if this is conceptually wrong, please let me know.

However, my app works now    :+1:

**Comment by myleftshoe** [comment] 2019-08-30 04:06
Thanks @vitalis-wiens this fixed it for tonejs:
```
intro: 'var global = typeof self !== undefined ? self : this;'
```
