### ISSUE TITLE
remove global check in favor of rollup-plugin-node-globals

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup-plugin-commonjs#98] opened 2016-09-06 15:46 UTC
if you feel strongly that `global` belongs in this module I can remove it from `rollup-plugin-node-globals`

**Comment by Rich-Harris** [comment] 2016-09-06 23:29
I think you're right that it belongs with the others. I wonder if we should make life easier for people by combining them into one plugin? It would also make builds faster since the code wouldn't need to be parsed a second time unnecessarily. What do you reckon?

**Comment by calvinmetcalf** [comment] 2016-09-07 11:56
I'd be in favor of the node-globals and possibly node-builtins being pulled in, we'd probably want to seperate it out from the commonjs parts of the code though as people may use the globals and builtins even without using a commonjs module

**Comment by calvinmetcalf** [comment] 2016-09-07 15:16
actually node-builtins probably would make sense to go into the path resolve one

**Comment by calvinmetcalf** [comment] 2016-09-17 13:47
so I see there are a lot of benefits to combining them, but I also see some benefits to keeping globals seperate is that especially once es6 modules come to node (whenever that is) globals plugin by itself will still be useful by it's self for those situations, what if the globals plugin could accept parsed ast/magicstring and then return them back so it could be called by this plugin internally while still being available on it's own ?

**Comment by Tylerian** [comment] 2019-07-29 22:36
I second this, as a side effect, it would also fix undefined module.exports errors caused by misplacing the rollup-plugin-node-globals before rollup-plugin-commonjs plugin in rollup config's plugin array.

**Comment by shellscape** [comment] 2019-11-24 18:12
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed by shellscape** 2019-11-24 18:12 UTC
Labels: discussion
