### ISSUE TITLE
'default' is not exported by, even with namedExports

### ISSUE THREAD

**Issue by binarykitchen** [rollup/rollup-plugin-commonjs#200] opened 2017-05-28 02:36 UTC
I have defined a custom named export like that in my rollup config

```
    commonjs({
      namedExports: {
        'node_modules/global/document.js': [ 'document' ]
      }
    }),
```

in the hope it fixed the following error but it doesn't:

```
~/c/videomail-client ❯❯❯ yarn test
yarn test v0.24.5
$ rollup -c env/test/rollup.config.js && cat tmp/test.js | tape-run 
100% (80): src/wrappers/visuals/replay.js⚠️   'default' is not exported by 'node_modules/global/document.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/global/document.js (1:145)
1: import * as document from "/home/michael-heuberger/code/videomail-client/node_modules/global/document.js"; export default ( document && document['default'] ) || document;
```

Am I missing something or is this a bug?

**Comment by binarykitchen** [comment] 2017-06-11 01:05
anyone?

**Comment by bfred-it** [comment] 2017-06-22 06:46
Duplicate of either https://github.com/rollup/rollup/issues/1408 or https://github.com/rollup/rollup-plugin-commonjs/issues/193 😅 Sorry about that

**Closed by bfred-it** 2017-06-22 06:46 UTC
Labels: duplicate

**Comment by yuvilio** [comment] 2017-08-20 22:53
I found that sometimes it's a matter of listing it in the `includes` part of the config.

ran into this issue when importing React (`import React from 'react'`) :

```bash
^@commonjs-proxy:/home/yuvilio/ws/apps/node/metalsmith/es6-scratch-notebook/node_modules/create-react-class/factory.js
default is not exported by node_modules/create-react-class/factory.js
1: import * as factory from "/home/yuvilio/ws/apps/node/metalsmith/es6-scratch-notebook/node_modules/create-react-class/factory.js"; export default ( factory && factory['default'] ) || factory;
```

I attempted to use the namedExports clause in a few ways but the warning kept showing. But when i added the module having the problem `create-react-class` into includes. the 
```js
// ...
import commonjs from 'rollup-plugin-commonjs'
// ...

// rollup props
export let baseProps = {
  format: 'iife',
  plugins: [
    commonjs({
      exclude: 'node_modules/process-es6/**',
      include: [
        'node_modules/fbjs/**',
        'node_modules/object-assign/**',
        'node_modules/react/**',
        'node_modules/react-dom/**',
        'node_modules/prop-types/**',
        'node_modules/create-react-class/**' // made that "default not exported by" error go away
      ]
    }),

  ],
};

```

**Comment by wilomgfx** [comment] 2018-08-14 18:31
@yuvilio  does not seem to work anymore :( seems like include does not take an array 🤔
