### ISSUE TITLE
Does not work with new version of react.

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-plugin-commonjs#240] opened 2017-10-04 21:36 UTC
So, I have no idea why, but this can't resolve the dependency of the new version of React...just figured it out through process of elimination. It seems like this would be able to resolve all the things webpack can. Can we not just copy that functionality? Is there any reason we would want to make that more difficult?

Sorry, I'm trying to ask that in as non condescending a way as I can, but as you can probably tell, it doesn't really make sense to me. Or is this just one of those low effort projects that no one really pays attention to?

**Comment by zwhitchcox** [comment] 2017-10-04 22:12
https://youtu.be/pqmd6rhMLb4

Made a video of the problem. This affects react 16.0.0 with the newest version of rollup (0.50.0) and commonjs (8.0.2)

**Comment by otsdr** [comment] 2017-10-05 07:08
Duplicate of #232

**Closed** 2017-10-05 14:21 UTC
