### ISSUE TITLE
Require inside if produces semantically different or invalid code

### ISSUE THREAD

**Issue by edsrzf** [rollup/rollup-plugin-commonjs#366] opened 2019-01-04 18:54 UTC
`rollup` version: 1.0.1
`rollup-plugin-commonjs` version: 9.1.3

When there is a `require` inside an `if` statement with no braces, the resulting bundle can be invalid or at least semantically very different. Consider these files:

```js
// main.js
if (Math.random() < 0.5)
  require('./mod.js');

// mod.js
foo = 1
```

Resulting IIFE bundle:
```js
var test = (function () {
  'use strict';

  foo = 1;

  if (Math.random() < 0.5) // <- Problem here

  var main = {

  };

  return main;

}());
```

A real-world example of where I ran into this was with the treo WebSQL plugin, here: https://github.com/treojs/treo/blob/master/plugins/treo-websql/index.js#L24

**Comment by shellscape** [comment] 2019-11-24 18:37
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:

**Closed by shellscape** 2019-11-24 18:37 UTC

**Comment by edsrzf** [comment] 2019-11-24 19:19
@shellscape I'm still able to replicate this issue with the latest versions of rollup and this plugin:

* `rollup`: 1.27.4
* `rollup-plugin-commonjs`: 10.1.0

**Comment by shellscape** [comment] 2019-11-24 19:23
@edsrzf OK thanks. Can you put together a very small repo that demonstrates a reproduction? We'll need it once the issue is transferred to the new repo.
