### ISSUE TITLE
Code generated for external re-exports by rollup isn't recognized by the plugin

### ISSUE THREAD

**Issue by marijnh** [rollup/rollup-plugin-commonjs#403] opened 2019-08-08 13:10 UTC
If you run rollup (generating CommonJS) on something like `export {Foo} from "foo"` while marking `"foo"` as external, you get code like this:

```
Object.defineProperty(exports, 'Foo', {
    enumerable: true,
    get: function () {
        return foo.Foo;
    }
});
```

But when you then try to consume the resulting package via rollup-plugin-comonjs, it'll complain

```
[!] Error: 'Foo' is not exported by node_modules/bar/dist/foo.js
```

Is there something I'm doing wrong? Is it unreasonable to expect Rollup's CommonJS output to be recognized by this plugin?

**Comment by marijnh** [comment] 2019-08-08 13:15
(Found a workaround with the `externalLiveBindings: false` option to Rollup, so if this is hard to support, I can live with a wontfix answer.)

**Comment by TrySound** [comment] 2019-08-08 13:21
This is the way I use in my app for react package
```js
import react from 'react';

commonjs({
  namedExports: {
    'react': Object.keys(react)
  }
})
```

**Comment by bterlson** [comment] 2019-08-08 21:34
Closing as duplicate of #159, please move any discussion over there!

FWIW rollup recognizing its own CJS in a mirror seems like a worthwhile enhancement, but these dynamic patterns are generally difficult to tease out reliably. `namedExports` is going to be the right solution (and @TrySound's dynamic approach seems really cool, I may adopt it 👍)

**Closed by bterlson** 2019-08-08 21:34 UTC
