### ISSUE TITLE
How to treat empty file

### ISSUE THREAD

**Issue by otakustay** [rollup/rollup-plugin-commonjs#194] opened 2017-04-26 09:34 UTC
Today I encountered an error using rollup and rollup-plugin-commonjs to bundle my lib:

```
'default' is not exported by 'node_modules/core-js/library/modules/es6.object.to-string.js'
```

After some research I find this issue comes from [core-js/library/modules/es6.object.to-string.js](https://github.com/zloirock/core-js/blob/master/library/modules/es6.object.to-string.js) being an emty file

I manually put a `module.exports = null` statement in this file then bundled my lib successfully, but I'm wondering if it can be handled by rollup-plugin-commonjs itself as an edge case

**Comment by jonataswalker** [comment] 2017-05-03 15:25
I solved this with - [rollup-plugin-hypothetical](https://www.npmjs.com/package/rollup-plugin-hypothetical):

```javascript
  plugins: [
    hypothetical({
      allowRealFiles: true,
      files: {
        './node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.to-string.js': 'export default null'
      }
    })
```

**Comment by otakustay** [comment] 2017-05-04 04:11
@jonataswalker Thanks for great hint, I'm also expecting rollup-plugin-commonjs can handle this properly since hypothetical plugin requires a fs path instead of a module name

**Comment by bfred-it** [comment] 2017-06-22 06:42
Duplicate of https://github.com/rollup/rollup/issues/1408

It still works regardless of the warning, right?

**Closed by bfred-it** 2017-06-22 06:42 UTC
Labels: duplicate

**Comment by trusktr** [comment] 2017-08-07 16:13
It does still work regardless of the warning. :)
