### ISSUE TITLE
SyntaxError when using core-js polyfills

### ISSUE THREAD

**Issue by rafaelfbs** [rollup/rollup-plugin-commonjs#33] opened 2016-01-23 18:43 UTC
When bundling code which uses getOwnPropertyNames, getPrototypeOf, etc, this error happens:

```javascript
SyntaxError: 'import' and 'export' may only appear at the top level (2:0) in /home/****/****/node_modules/core-js/library/modules/$.is-object.js
    at Parser.pp$4.raise (/home/****/****/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:4271:13)
    at Parser.pp$1.parseStatement (/home/****/****/node_modules/gulp-rollup/node_modules/rollup/dist/rollup.js:2836:29)
```

My code:

```javascript
function propertiesOf(klass) {
  let proto = klass;
  let props = [];
  let keys;

  do {
    proto = Object.getPrototypeOf(proto);
    keys  = Reflect.ownKeys(proto);

    props = props.concat(
      keys.filter(key => props.indexOf(key) < 0)
    );
  }
  while (typeof proto === 'function');

  return props;
}
```
The transformed code of "$.is-object.js" after commonjs plugin:

```javascript
var $_isObject = __commonjs(function (module) {
import _typeof from 'babel-runtime/helpers/typeof';
module.exports = function (it) {
  return (typeof it === 'undefined' ? 'undefined' : _typeof(it)) === 'object' ? it !== null : typeof it === 'function';
};
});

export default ($_isObject && typeof $_isObject === 'object' && 'default' in $_isObject ? $_isObject['default'] : $_isObject);
```

**Comment by darlanalves** [comment] 2016-02-06 17:49
This is quite common with other libraries or app codes as well. 

The problem is due to `import` clauses inserted in the same place of `require()` calls. All the import declarations should be moved to the top of the file to fix this.

A similar code that will probably break too:
```
var fs = require('fs');

function readFile(file) {
  // this will be turned into a import directive
  var path = require('path');

  var fullPath = path.join(__dirname, file);
  return fs.createReadStream(fullPath);
}

// ...
```

**Comment by Rich-Harris** [comment] 2016-09-17 18:24
Sorry for leaving this open such a long time. This is fixed in recent versions of the plugin – closing

**Closed by Rich-Harris** 2016-09-17 18:24 UTC
