### ISSUE TITLE
including commonjs module with binary required files

### ISSUE THREAD

**Issue by jkuri** [rollup/rollup-plugin-commonjs#101] opened 2016-09-14 15:05 UTC
Hey,

What would be the solution to include commonjs modules that comes with binaries included?
Is that the issue on this plugin side or I am doing it wrong in configuration somehow?

I got i.e. `SyntaxError: Unexpected character '�' (1:0) in ../node_modules/child_pty/build/Release/pty.node`.. which is reasonable that rollup can't roll the binaries in the code. Searching for this but I did non found any solution.

**Comment by Rich-Harris** [comment] 2016-09-17 15:44
Can you supply a minimal reproduction so that we can start to investigate? Thanks 👍

**Comment by jkuri** [comment] 2016-09-17 20:59
Hey @Rich-Harris,

I prepared repository that reproduces that at https://github.com/jkuri/rollup-repro-binary-commonjs. I encountered that issue when bundling a module for `electron` app and solved it with manually copying `child_pty` binaries in `dist/` directory in a npm postinstall script with a rollup configuration setted i.e.:
```js
paths: {
  'child_pty': './vendor/child_pty'
}
```
so `require` finds it there.
Is this the best solution for now? It would be nice if that plugin would automatically manage binaries that comes from 3rd party packages. Otherwise, thanks for this plugin and checking out on this!

**Comment by Rich-Harris** [comment] 2016-09-18 02:42
I think the best solution might eventually be to create rollup-plugin-node-addons, which would replace addons with placeholders and copy them to a destination of your configuration:

```js
import nodeAddons from 'rollup-plugin-node-addons';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'src/index.js',
  dest: 'dist/bundle.js',
  format: 'cjs',
  plugins: [
    nodeAddons({ dest: 'dist/addons' }),
    nodeResolve(),
    commonjs()
  ]
};
```

Any `.node` files would be intercepted by the plugin and copied to the `dest` option, and they'd be imported via relative paths from `dist/bundle.js`.

For now though, your workaround (basically doing the same thing manually) is probably the best option. Thanks for the repro and explanation of the problem.

**Comment by jkuri** [comment] 2016-09-18 04:09
Additional plugin sounds fair enough. 
I just checked and `node-sass` for example provides `.gyp` extension naming for their binaries, so it is neccesarily a `.node`, might also be without extension, I think. The plugin should detect if a imported file is instance of blob or something and copy it if so. Thank you for checking. Also, let me know if I can help to work on this plugin.

**Comment by cwadrupldijjit** [comment] 2018-07-25 23:08
Is this issue going anywhere?  I was trying to use Rollup to bundle an electron app with the `keytar` package, which has native bindings so it can interact with OS keychains.  I've used this plugin to include node_modules like `keytar`, and by default it "supports" `.node` extensions (which I've derived while looking at the source code), though it really doesn't actually do something with it--it really tries to pull it in and parse it even though it is binary, just as mentioned above.

I had been following the idea of creating a package to deal with it, but since this conversation is a nearly a couple of years old (at least from the last message), I want to make sure that there isn't a solution out there already to see if it's worth investing time into this or not.

**Comment by cwadrupldijjit** [comment] 2018-08-01 21:18
I started into that example and found that super simple.  I'll have to test it a bit and then maybe I could release that on npm or something.

**Comment by frank-dspeed** [comment] 2019-02-17 21:14
@cwadrupldijjit do you got any existing code to check and improve?

**Comment by cwadrupldijjit** [comment] 2019-03-09 17:20
Apologies for not seeing this sooner--I largely have ignored the notifications from GitHub because I haven't gone through to unwatch repos I don't need to watch.

I'll have to look into this again.  I think I was able to get something that sorta worked for this, though I haven't worked on that project in quite a while since it was a personal projects and work got in the way.  It had something to do with the `this.emitAsset()` method in the documentation, which moved here:
https://rollupjs.org/guide/en#this-emitasset-assetname-string-source-string-string

I'll have to paste code snippets of my solution, though.  I'll have to also see what I should do about making the plugin into an NPM package and making it easier for you to use it, too.

**Comment by shellscape** [comment] 2019-11-24 18:12
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed by shellscape** 2019-11-24 18:12 UTC
Labels: enhancement
