### ISSUE TITLE
require is undefined

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-plugin-commonjs#239] opened 2017-10-04 16:58 UTC
I'm getting the error

```
bundle.js:4 Uncaught ReferenceError: require is not defined
    at bundle.js:4
```

This is my rollup config:

```js
  1 import json from 'rollup-plugin-json'
  2 import commonjs from 'rollup-plugin-commonjs'
  3 import nodeResolve from 'rollup-plugin-node-resolve'
  4 import babel from 'rollup-plugin-babel'
  5 import serve from 'rollup-plugin-serve'
  6 import livereload from 'rollup-plugin-livereload' 
  7 
  8 export default {           
  9   input: 'src/main.js',    
 10   output: {                
 11     file: 'dist/bundle.js',
 12     format: 'cjs',
 13   },
 14   plugins: [
 15     nodeResolve({          
 16       jsnext: true,        
 17       main: true
 18     }),
 19     commonjs({
 20       include: ["node_modules/**"],
 21     }),     
 22     json(),
 23     babel({
 24       exclude: 'node_modules/**',
 25     }),
 26     serve({
 27       historyApiFallback: true,
 28       contentBase: ['dist', 'static'],
 29     }),
 30     livereload(),
 31   ]   
 32 }     
```

Is this plugin supposed to define require, or do I need another plugin for that?

**Comment by zwhitchcox** [comment] 2017-10-05 19:00
This is reproducable by cloning my repository here: https://github.com/zwhitchcox/rollup-starter/tree/0f08d02da19305ca3945ad29f53b9bbb1ee88224

**Comment by zwhitchcox** [comment] 2017-10-05 19:00
Works with import in src/main.js, but doesn't work with require...I thought commonjs was supposed to interpret require?

**Comment by yvele** [comment] 2017-10-19 08:42
Same problem here.. my code is being built to:

```js
var Test = (function () {
'use strict';

var bar = require("./bar.js");

var foo = function () {
  return bar;
};

return foo;

}());
```

**Comment by Rich-Harris** [comment] 2017-10-19 12:31
The issue here is that you can't mix `require` and `import`/`export`. This plugin only transforms CommonJS modules, and if you have an `import` or `export` declaration it means that the file is an ES module, not a CommonJS one.

**Comment by yvele** [comment] 2017-10-19 12:54
Ok I get it, this is by design https://github.com/rollup/rollup/issues/1058#issuecomment-254187433

The problem is that I come from Webpack where mixing the two things is not a problem

Thanks @Rich-Harris

**Comment by yvele** [comment] 2017-10-19 12:55
PS: Don't you think a clear and explicit error message (or warning) would be quite useful for developers?

**Comment by tswaters** [comment] 2017-12-24 04:31
I was having a heck of a time with the same error message.  I didn't actually use any imports, but `babel-preset-env` was pulling them in for me, and this module was stubbornly not doing anything and leaving nested require statements in the bundle.

In trying to create an isolated test case, I ended up trying to rejig the order the the plugins, and, sure enough, that makes it work....  to me it makes sense that babel would need to go first to pull in the polyfill imports, but this is not the case, and with the opposite, everything is transpiled properly.

```js
// before -- not working:
plugins: [
  babel(),
  resolve(),
  commonjs(),
]

// after -- working:
plugins: [
  resolve(),
  commonjs(),
  babel()
]
```

**Comment by jcubic** [comment] 2018-06-11 14:54
I'm trying to bundle yargs library and have this as output:
```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (factory());
}(this, (function () { 'use strict';

  // classic singleton yargs API, to use yargs
  // without running as a singleton do:
  // require('yargs/yargs')(process.argv.slice(2))
  const yargs = require('./yargs');

  Argv(process.argv.slice(2));

  module.exports = Argv;

  function Argv (processArgs, cwd) {
    const argv = yargs(processArgs, cwd, require);
    singletonify(argv);
    return argv
  }

  /*  Hack an instance of Argv with process.argv into Argv
      so people can do
      require('yargs')(['--beeble=1','-z','zizzle']).argv
      to parse a list of args and
      require('yargs').argv
      to get a parsed version of process.argv.
  */
  function singletonify (inst) {
    Object.keys(inst).forEach((key) => {
      if (key === 'argv') {
        Argv.__defineGetter__(key, inst.__lookupGetter__(key));
      } else {
        Argv[key] = typeof inst[key] === 'function' ? inst[key].bind(inst) : inst[key];
      }
    });
  }

})));
```

why there is require and not the result? I've tried with and without resolve()  with no success.

**Comment by yeyuguo** [comment] 2018-09-10 05:08
wrong:` Uncaught ReferenceError: require is not defined`
```js
plugins: [
        builtins(), //  import builtins from 'rollup-plugin-node-builtins';
        commonjs(), // import commonjs from 'rollup-plugin-commonjs';
        
]
```
I changed config like this:
```js
plugins: [
        // commonjs before bultins      
        commonjs(), // import commonjs from 'rollup-plugin-commonjs';
        builtins(), //  import builtins from 'rollup-plugin-node-builtins';
]
```
It works fine!

**Comment by andyhu** [comment] 2019-01-10 03:36
Have you guys solved the problem? I'm constantly having issue using commonjs, node-resolve and node-globals.

**Comment by relu91** [comment] 2019-02-27 16:20
I'm having the same issue with node-globals and commonjs plugin. I've made a simple project to reproduce the issue.
https://github.com/relu91/rollup239

**Comment by nickzwaans** [comment] 2019-03-13 11:08
I've included react and react-dom in my index.html file from a CDN, then used the following rollup config to compile everything, using browsersync to serve. Maybe someone will find this usefull (:

```
import babel from "rollup-plugin-babel";
import resolve from "rollup-plugin-node-resolve";
import postcss from "rollup-plugin-postcss";
import commonjs from "rollup-plugin-commonjs";
import progress from "rollup-plugin-progress";
import browsersync from "rollup-plugin-browsersync";

const NODE_ENV = process.env.NODE_ENV || "development";
const outputFile = NODE_ENV === "production" ? "./prod.js" : "./dev.js";
const extensions = ['.js', '.jsx'];
const externals = {
  'react' : 'React',
  'react-dom' : 'ReactDOM',
  'react-scripts' : 'ReactScripts',
};

let production = true;
if (NODE_ENV === "development") {
  production = false;
}

export default {
  input: ["./src/index.js"],
  output: {
    file: outputFile,
    format: "iife",
    sourcemap: true,
    globals: externals,
  },
  plugins: [
    resolve(),
    commonjs({
      include: ["node_modules/**"],
    }),
    babel({
      extensions,
      exclude: 'node_modules/**',
    }),
    sass(),
    postcss(),
    progress(),
    !production && browsersync({server: 'public'})
  ],
  external: Object.keys(externals),
};```

**Comment by chiguireitor** [comment] 2019-04-26 16:47
@tswaters solution is ok.... the good thing after searching for this non-stop is that now i don't need hair care products anymore, so that's a plus

**Comment by funkybob** [comment] 2019-08-28 02:04
Just a note for future sufferers: I _can't_ reorder as suggested, because then the React guff $DAYJOB wants me to work on confuses the parser... babel _must_ come before commonjs for me, else commonjs complains "SyntaxError: Unexpected token".

**Comment by shellscape** [comment] 2019-11-24 18:18
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Closed by shellscape** 2019-11-24 18:18 UTC

**Comment by donut** [comment] 2019-11-25 18:42
For those who may run into this issue as I did today, the solution I found was this specific plugin order along with setting `browser: true` for `nodeResolve()`:

```js
    [ nodeResolve({ browser:true, preferBuiltins: true })
    , commonjs({ namedExports: {axios: ['get']} })
    , globals()
    , builtins()
    , json()
    , babel
      ({ exclude: 'node_modules/**'
       , presets: [['@babel/preset-env', {useBuiltIns: 'entry', corejs: 3}]]
       })
    , postcss
      ({ extensions: ['.css', '.less']
       , extract: resolve(css_prefix + '.css')
       , plugins: [autoprefixer()] }) ]
```
